### ISSUE TITLE
Fresh install: ImportError: No module named 'yaml' on MacOS High Sierra 

### ISSUE THREAD

**Issue by ryellow** [randy3k/R-Box#118]
Hello,
I am trying to install R-Box in a fresh install of Sublime Text 3 on MacOS High Sierra. 
Installed Package Control successfully.
Then Install Package Control: R-Box and the console reply with the following:

`....
reloading settings Packages/User/Package Control.sublime-settings
Package Control: No updated packages
ignored packages updated to: ["R-Box", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' has successfully been installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' has successfully been installed or updated
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin R-Box.rbox
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "rbox in /Users/myname/Library/Application Support/Sublime Text 3/Installed Packages/R-Box.sublime-package", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "box in /Users/myname/Library/Application Support/Sublime Text 3/Installed Packages/R-Box.sublime-package", line 3, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "box.popup in /Users/myname/Library/Application Support/Sublime Text 3/Installed Packages/R-Box.sublime-package", line 4, in <module>
  File "/Users/myname/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 27, in <module>
    from . import frontmatter
  File "/Users/myname/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/frontmatter.py", line 2, in <module>
    import yaml
ImportError: No module named 'yaml'
`

**Comment by randy3k** [comment]
Thanks, it is because new version of mdpop requires `pymdownx` and `pyyaml`. 

fixed now. An update will be soon be available via Package Control.
