### ISSUE TITLE
R-box menu items about package install, test, build not work in windows

### ISSUE THREAD

**Issue by kongdd** [randy3k/R-Box#121]
I am using R-box in sublime text3 build 3143, win10 system. 
R-box menu items about package install, test, build not work in windows.

How can I configure it to work normally?

**Comment by randy3k** [comment]
You have to install SendCode to enable them. Basically, the mean will send the relevant code to your chosen R program.

**Comment by kongdd** [comment]
Thanks for you quick response. I will have a try.
Thanks very much!

**Comment by kongdd** [comment]
Do you have any suggestion about this error?
I have installed ConEmuC and SendCode.
In Rstudio, this package can be built normally. But it can't work in R-box.

`Traceback (most recent call last):
  File "C:\Users\kongdd\AppData\Roaming\Sublime Text 3\Packages\SendCode\send_code.py", line 88, in <lambda>
    sublime.set_timeout_async(lambda: sender.send_text(cmd))
  File "C:\Users\kongdd\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\sender.py", line 131, in send_text
    super(RCodeSender, self).send_text(cmd)
  File "C:\Users\kongdd\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\sender.py", line 95, in send_text
    self.send_to_cmder(cmd)
  File "C:\Users\kongdd\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\sender.py", line 54, in send_to_cmder
    send_to_cmder(cmd, conemuc, bracketed=self.bracketed_paste_mode)
  File "C:\Users\kongdd\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\conemu\__init__.py", line 73, in send_to_cmder
    _send_to_conemu(cmd, conemuc, bracketed)
  File "C:\Users\kongdd\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\conemu\__init__.py", line 93, in _send_to_conemu
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 547, in check_call
subprocess.CalledProcessError: Command 'C:\Program Files\ConEmu\ConEmu\ConEmuC.exe -GuiMacro:0 Paste(2,"devtools::document(\"F:\\\\Github\\\\R\\\\Ipaper\")")' returned non-zero exit status 134
`

**Comment by randy3k** [comment]
Did you open ConEmu?

**Comment by kongdd** [comment]
Thanks very much!  Open ConEmu and entry R, works now. A very powerful sublime package and save a lot of time in RStudio.
