### ISSUE TITLE
r-box popup hints not shown

### ISSUE THREAD

**Issue by chrisoswald** [randy3k/R-Box#129]
Hello,
I habe installed r-box and all dependencies but the popup-hints don't appear. By typing any r-command only the autocomplete appear.  Any idea what i can do?

Christian

I use Linuxmint 18.3, sublime 3.1.1 build 3176., packages (Color Highlighter,  PyV8,                                    SublimeLinter-rubocop,   Emmet ,  Rails Developer Snippets,  SublimeLinter-ruby ,                   
AdvancedNewFile, GitSavvy, R-Box,  SublimeLinter, All Autocomplete,  LSP,  R-snippets ,                TerminalView, BracketHighlighter, Package Control, SCSS, Whitespace )

**Comment by randy3k** [comment]
Is there any error messages from the console?

**Comment by chrisoswald** [comment]
No I cannot see anything


`
DPI scale (detected): 1
startup, version: 3176 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/cosw/.config/sublime-text-3/Packages
state path: /home/cosw/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/cosw/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.104634
startup time: 0.193931
first paint time: 0.199912
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin All Autocomplete.all_views_completions
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin Emmet.emmet-plugin
reloading plugin GitSavvy.__init__
reloading plugin GitSavvy.git_savvy
reloading plugin LSP.boot
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin R-Box.rbox
reloading plugin SCSS.scss_completions
reloading plugin SublimeLinter-rubocop.linter
rubocop: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
reloading plugin SublimeLinter-ruby.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin TerminalView.exec
reloading plugin TerminalView.gateone_terminal_emulator
reloading plugin TerminalView.linux_pty
reloading plugin TerminalView.pyte_terminal_emulator
reloading plugin TerminalView.sublime_terminal_buffer
reloading plugin TerminalView.sublime_view_cache
reloading plugin TerminalView.TerminalView
reloading plugin TerminalView.utils
reloading plugin Whitespace.Whitespace
reloading plugin BeautifyRuby.beautify_ruby
reloading plugin Enhanced-R.Enhanced-R
reloading plugin GitGutter.plugin
reloading plugin GitGutter.release
reloading plugin SendCode.choose_prog
reloading plugin SendCode.install_xdotool
reloading plugin SendCode.send_code
reloading plugin SendCode.settings
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "/home/cosw/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package/main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  File "/home/cosw/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package/main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "/home/cosw/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package/main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "/home/cosw/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package/main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "/home/cosw/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package/color_scheme.py", line 43, in parse_color_scheme
    color_scheme_xml = ElementTree.fromstring(color_scheme_content)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-06-27 08:17:46, next run at 2018-06-27 09:17:46 or after

`

**Comment by randy3k** [comment]
I saw you have installed Enhanced R, please remove it as it may confuse SublimeText.

**Comment by chrisoswald** [comment]
I have dropped the whole sublime config and reinstalled all, now the hints appear.
Thank you very much, it's nice working with it.
