### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by dacarras** [randy3k/R-Box#60]
Hi randy3k, 

I cannot get R-box to work. It was working fine before (1 day a go), so I re install sublime 3 and R-box. I did try REPL, but it work in unstable manner (sometime it took the code, and other it didn't). So is not option for now.

The error I get in the console is the following:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "rbox.send_text in C:\Users\dacarras\AppData\Roaming\Sublime Text 3\Installed Packages\R-Box.sublime-package", line 206, in run
  File "rbox.send_text in C:\Users\dacarras\AppData\Roaming\Sublime Text 3\Installed Packages\R-Box.sublime-package", line 150, in send_text
  File "rbox.send_text in C:\Users\dacarras\AppData\Roaming\Sublime Text 3\Installed Packages\R-Box.sublime-package", line 98, in _send_text_ahk
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

For what I've seen, this might be an specific issue with x64 windows machine, though I'm entirely sure. Hopefully, you could give a hint to make it work again. Thanks!

**Comment by randy3k** [comment]
Hi dacarras,

R-Box gets some updates recently and I didn't test it well enough. It should be fixed now. Try reinstalling R-Box.

**Comment by dacarras** [comment]
Now it works with no problem!
Cheers!
@randy3k
